blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Support
    url: https://github.com/Amayyas/SkyPulse/discussions
    about: Please ask questions and get support here instead of opening issues.
